name: Wire Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  C3_ENV: ci

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pustovitDmytro/redis-github-action@v1.0.1

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Cache Clojure Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install Clojure CLI
        run: |
          curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
          chmod +x linux-install.sh
          sudo ./linux-install.sh

      - name: Run Clojure Tests
        run: clojure -M:test:spec-ci

      - name: Run ClojureScript Tests
        run: clojure -M:test:cljs once
